### ISSUE TITLE
Some key scripts are in .gitignore

### ISSUE THREAD

**Issue by onenoc** [OpenNLPLab/lra#1]
Hi,

Some key scripts, including run_task.sh, are in the .gitignore file. Can you include them?

Thanks

**Comment by Doraemonzzz** [comment]
Thank you for your reminder, we have added the run_task.sh script in the Tnn codebase, since this repo only contains source code, so we will not add any scripts here.

**Comment by onenoc** [comment]
Thank you, will check it out!
