### ISSUE TITLE
Benchmark configs missing

### ISSUE THREAD

**Issue by jonathanmei** [OpenNLPLab/lra#2]
Hi, great work! I was trying to replicate some benchmarks, but found a few models do not run (Linformer, Nystromformer, Reformer). Could you please help? Thanks!

**Comment by jonathanmei** [comment]
I realized that the model config `.yaml` files have `max_seq_len=1000` as default, but that value should be set to `4096` for the `imdb` dataset. But I'm also seeing that the default configs from those files don't quite seem to correspond to what's shown in the bubble plot on the left of Figure 1 of the TNN paper. Where could I find those hyperparameters?

**Comment by Doraemonzzz** [comment]
> Hi, great work! I was trying to replicate some benchmarks, but found a few models do not run (Linformer, Nystromformer, Reformer). Could you please help? Thanks!

Hi, the config of models such as Linformer and Nystromformer have not been added to the codebase, but we have implemented them in `lra/src/models/sequence/x_attention`. To reproduce these methods (taking linformer as an example), you should first add linformer.yaml in `lra/configs/model`, and then add `linformer-lra-xxx.yaml` in `lra/configs/experiment`, where `xxx` is aan, imdb and other tasks.

**Comment by Doraemonzzz** [comment]
> I realized that the model config `.yaml` files have `max_seq_len=1000` as default, but that value should be set to `4096` for the `imdb` dataset. But I'm also seeing that the default configs from those files don't quite seem to correspond to what's shown in the bubble plot on the left of Figure 1 of the TNN paper. Where could I find those hyperparameters?

For figure1, all the models are tested based on the imdb task, the config is tno-lra-imdb.yaml, and the rest of the models can be adjusted to a comparable size. For the imdb task, the original paper mentioned that the sequence lengths of 1k, 2k, 3k, and 4k can be used. In particular, we used 1k here.

**Comment by jonathanmei** [comment]
> Hi, the config of models such as Linformer and Nystromformer have not been added to the codebase, but we have implemented them in `lra/src/models/sequence/x_attention`. To reproduce these methods (taking linformer as an example), you should first add linformer.yaml in `lra/configs/model`, and then add `linformer-lra-xxx.yaml` in `lra/configs/experiment`, where `xxx` is aan, imdb and other tasks.

Thanks for the quick reply! Yep, I've actually gotten those models to run, which is what part of my 2nd comment was about.

> For figure1, all the models are tested based on the imdb task, the config is tno-lra-imdb.yaml, and the rest of the models can be adjusted to a comparable size. For the imdb task, the original paper mentioned that the sequence lengths of 1k, 2k, 3k, and 4k can be used. In particular, we used 1k here.

Exactly. Since there are many ways to adjust each model to a comparable size, I was hoping you would be able to provide the hyperparameters that you used in the paper to be able to reproduce your results. Thanks again!

**Comment by Doraemonzzz** [comment]
> > Hi, the config of models such as Linformer and Nystromformer have not been added to the codebase, but we have implemented them in `lra/src/models/sequence/x_attention`. To reproduce these methods (taking linformer as an example), you should first add linformer.yaml in `lra/configs/model`, and then add `linformer-lra-xxx.yaml` in `lra/configs/experiment`, where `xxx` is aan, imdb and other tasks.
> 
> Thanks for the quick reply! Yep, I've actually gotten those models to run, which is what part of my 2nd comment was about.
> 
> > For figure1, all the models are tested based on the imdb task, the config is tno-lra-imdb.yaml, and the rest of the models can be adjusted to a comparable size. For the imdb task, the original paper mentioned that the sequence lengths of 1k, 2k, 3k, and 4k can be used. In particular, we used 1k here.
> 
> Exactly. Since there are many ways to adjust each model to a comparable size, I was hoping you would be able to provide the hyperparameters that you used in the paper to be able to reproduce your results. Thanks again!

For some reason, the config is not on my side, I will get these configs ASAP, and add them to the codebase.
